logging:
  level: INFO
  loggers:
    com.aphiwe.jdbi3: DEBUG
database:
  driverClass: com.mysql.jdbc.Driver
  url:  jdbc:mysql://localhost:3306/StudentDB
  user: root
  password: test1234

  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s

  validationQuery: "SELECT 1"

  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32

  checkConnectionWhileIdle: false

  evictionInterval: 10s

  minIdleTime: 1 minute
server:
  maxThreads: 512
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  rootPath: /api/*